name: Backend CI

on:
  workflow_call:   # Make it reusable

jobs:
  build-backend:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    env:
      MONGO_URI: ${{ inputs.MONGO_URI }}
      JWT_SECRET: ${{ inputs.JWT_SECRET }}
      CLIENT_URL: ${{ inputs.CLIENT_URL }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: backend

      - name: Start Backend
        run: |
          npm start &
          echo "Waiting for backend to start..."
          npx wait-on http://localhost:5000
        working-directory: backend
