name: Frontend CI

on:
  workflow_call:
    inputs:
      REACT_APP_API_URL:
        description: "Backend API URL"
        required: true
        type: string

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: ${{ inputs.REACT_APP_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Build Frontend
        run: |
          CI=false npm run build
        working-directory: frontend
