name: Master Pipeline 1

on:
  workflow_call:

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml
    with:
      REACT_APP_API_URL: http://localhost:5000/api

  backend:
    needs: frontend
    uses: ./.github/workflows/backend.yml
    secrets:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}