name: Master Pipeline 1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Frontend CI
        run: |
          cd frontend
          npm install
          CI=false npm run build

      - name: Run Backend CI
        run: |
          cd backend
          npm install
          npm start &
          npx wait-on http://localhost:5000
